apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org//directory
    email: mateuslima90@gmail.com
    privateKeySecretRef:
      name: lesencrypt-tls
    solvers:
    - http01:
        ingress:
          class: nginx